#!/bin/bash
# KindleKraft Launcher
# Penguins184
# 04/2025

echo "===KindleKraft==="
if ! ls /mnt/us/kindlekraft-*/ > /dev/null 2>&1; then
    echo "KindleKraft Not Installed!"
    exit 1
fi

# Swapfile Stuff
if [ ! -f /mnt/base-us/swapfile ]
then
    echo "Missing Swapfile!"
    sleep 0.5
    echo "Please Select Swapfile Size."
    echo
    echo "1) 64M; Too Small"
    echo "2) 128M; Small"
    echo "3) 256M; *Recommended*"
    echo "4) 512M; Too Large!"
    read -p "Please Select 1-4:" s
    echo "Creating Swapfile! Please Wait..."
    case $s in
    1)
        dd if=/dev/zero of=/mnt/base-us/swapfile bs=1M count=64
    ;;
    2)
        dd if=/dev/zero of=/mnt/base-us/swapfile bs=1M count=128
    ;;
    3)
        dd if=/dev/zero of=/mnt/base-us/swapfile bs=1M count=256
    ;;
    4)
        dd if=/dev/zero of=/mnt/base-us/swapfile bs=1M count=512
    ;;
    *)
        echo "Unknown Option! Swapfile Set To 256M."
        dd if=/dev/zero of=/mnt/base-us/swapfile bs=1M count=256
    ;;
    esac
    echo "Finishing Up..."
    mkswap /mnt/base-us/swapfile
    echo "Complete!"
fi

# Server Wizard

help() {
    echo "Welcome To KindleKraft!"
    echo
    echo "Usage: kindlekraft [-flag]"
    echo "Options:"
    echo "--help/-h: Show This Message,"
    echo "--version/-v: Show Versions,"
    echo "--start/-s: Start Server,"
    echo "--ip/-i: Get Private IPv4,"
    echo "--rswap/-r: Reset Swapfile,"
    echo "--edit/-e: CD Into Server Directory"
    echo "--reinstall/-re: Reinstall Server (DELETES CURRENT!)"
    echo
    echo "The Server Is Pre-Setup With Optimisations."
    echo "Reinstalling Downloads The Latest Kindle-Optimised Server From Github."
};

# Wizard Logic
if [ "$1" = "--help" ] || [ "$1" = "-h" ] # Help Command
then
    help
elif [ "$1" = "--version" ] || [ "$1" = "-v" ] #  Version Command
then
    echo "KindleKraft Hardcoded Versions:"
    echo "KindleKraft: 1.1.0,"
    echo "Java: 8u442b06 (Zulu: 8.84.0.15 - Arm32 SF),"
    echo "Server: [Default On Install] Spigot 1.7-1.8[.X],"
    echo "Last Changed: 04/2025."
elif [ "$1" = "--start" ] || [ "$1" = "-s" ] # Start Command
then
    echo "KindleKraft: Running Start Batchfile..."
    cd /mnt/us/kindlekraft-*/Server
    chmod +x ./Start.sh # Just In Case!
    ./Start.sh
elif [ "$1" = "--ip" ] || [ "$1" = "-i" ] # IP Retrieval Command
then
    echo "(KindleKraft) Private IP: "
    ip -f inet -o addr show | awk '{print $4}' | cut -d/ -f1 | grep -E '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)'
elif [ "$1" = "--rswap" ] || [ "$1" = "-r" ] # Reset Swapfile Command
then
    rm /mnt/base-us/swapfile
    echo "Deleted Swapfile!"
    echo "Run 'kindlekraft' Again To See The Swap Menu."
elif [ "$1" = "--edit" ] || [ "$1" = "-e" ] # Edit/CD Server Command
then
    cd /mnt/us/kindlekraft-*/Server
    echo "CD'ed Into The KindleKraft Server!"
elif [ "$1" = "--reinstall" ] || [ "$1" = "-re" ] # Reinstall Server Command
then
    echo TODO! Setup Github Repository.
else # Default To Help If Optionless
    help
fi